version: '3.4'

services:
  db:
    image: postgres:10.8-alpine
    networks:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - docker/db/.env
    ports:
      - 5432:5432


  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile_local
    networks:
      - db
    volumes:
      - ./:/app
    command: |
      /usr/bin/env sh -c "wait-for db:5432 --
        python manage.py collectstatic --noinput
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000"
    env_file:
      - docker/app/.env
      - docker/db/.env
    ports:
      - 8000:8000
    depends_on:
      - db


networks:
  db:
    driver: bridge

volumes:
    pgdata:
      name: centrosvita_db
      driver: local