version: '3.4'

services:
  app:
    image: "${IMAGE}"
    network_mode: host
    volumes:
      - /home/admin/public/:/home/admin/public/
    command: |
      /usr/bin/env sh -c "python manage.py collectstatic --noinput
        python manage.py migrate
        python manage.py compilemessages
        gunicorn config.wsgi --bind=127.0.0.1:8001"
    env_file:
      - env/app.env
      - env/db.env
    logging:
      driver: syslog
      options:
        tag: docker/app