# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200914_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='profiles',
            field=models.ManyToManyField(related_name='Profiles', to='profiles.Profile'),
        ),
    ]
