# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-24 20:38
from __future__ import unicode_literals

import centr_osvita.blogs.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.SlugField(verbose_name='Article url')),
                ('image', models.ImageField(upload_to=centr_osvita.blogs.models.post_image_path, verbose_name='Image')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
