# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-03 12:16
from __future__ import unicode_literals

import centr_osvita.blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.SlugField(verbose_name='Article url')),
                ('image', models.ImageField(upload_to=centr_osvita.blogs.models.post_image_path, verbose_name='Image')),
            ],
        ),
    ]
