# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-10 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Publish'),
        ),
    ]
